services:
  web:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: moodle_web
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html:cached
      - ./moodledata:/var/www/moodledata:cached
    env_file: .env
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: moodle_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE:    "${DB_NAME}"
      MYSQL_USER:        "${DB_USER}"
      MYSQL_PASSWORD:    "${DB_PASSWORD}"
      TZ:                ${TZ}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:                # optional
    image: phpmyadmin/phpmyadmin
    container_name: moodle_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST:      db
      PMA_PORT:      3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      TZ:                ${TZ}
    depends_on:
      - db

volumes:
  db_data:
